CREATE TABLE IF NOT EXISTS contacts (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  contact_number TEXT NOT NULL,
  contact_type TEXT NOT NULL,
  company_name TEXT NOT NULL,
  company_type TEXT,
  organization_number TEXT,
  vat_number TEXT,
  personal_number TEXT,
  contact_persons JSONB NOT NULL DEFAULT '[]',
  addresses JSONB NOT NULL DEFAULT '[]',
  email TEXT,
  phone TEXT,
  phone2 TEXT,
  website TEXT,
  tax_rate TEXT,
  payment_terms TEXT,
  currency TEXT,
  f_tax TEXT,
  notes TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);
