// client/src/plugins/profixio/mock-data.ts
// PLACEHOLDER DATA - This file will be deleted later
// Mock data for prototyping the Profixio plugin UI

import { ProfixioMatch } from './types/profixio';

export const mockMatches: ProfixioMatch[] = [
  {
    id: '1',
    tournamentId: '101',
    number: '1',
    name: 'Match 1',
    gameRound: 1,
    date: '2024-03-15',
    time: '19:00:00',
    datetimeStart: '2024-03-15T19:00:00Z',
    homeTeam: {
      teamRegistrationId: '201',
      globalTeamId: '301',
      name: 'IFK Malmö',
      goals: 3,
      isWinner: true,
    },
    awayTeam: {
      teamRegistrationId: '202',
      globalTeamId: '302',
      name: 'Malmö FF',
      goals: 1,
      isWinner: false,
    },
    hasWinner: true,
    winnerTeam: 'IFK Malmö',
    field: {
      id: '401',
      name: 'Plan 1',
      arena: {
        id: '501',
        arenaName: 'Malmö Arena',
      },
    },
    matchCategory: {
      id: '601',
      name: 'Division 1',
      categoryCode: 'DIV1',
    },
    matchGroup: {
      id: '701',
      displayName: 'Grupp A',
      name: 'Group A',
    },
    matchUrl: 'https://www.profixio.com/match/1',
    matchDataUpdated: '2024-03-15T20:30:00Z',
    resultsUpdated: '2024-03-15T20:30:00Z',
    sets: [
      { home: 25, away: 20 },
      { home: 25, away: 22 },
      { home: 20, away: 25 },
    ],
    periodInfo: {
      periodLength: 45,
      slotLength: 15,
      numberOfPeriods: 2,
      pauseLength: 15,
      extraPeriodLength: null,
    },
    isGroupPlay: true,
    isLeaguePlay: false,
    isPlayoff: false,
  },
  {
    id: '2',
    tournamentId: '101',
    number: '2',
    name: 'Match 2',
    gameRound: 1,
    date: '2024-03-16',
    time: '18:30:00',
    datetimeStart: '2024-03-16T18:30:00Z',
    homeTeam: {
      teamRegistrationId: '203',
      globalTeamId: '303',
      name: 'Helsingborgs IF',
      goals: 2,
      isWinner: false,
    },
    awayTeam: {
      teamRegistrationId: '201',
      globalTeamId: '301',
      name: 'IFK Malmö',
      goals: 4,
      isWinner: true,
    },
    hasWinner: true,
    winnerTeam: 'IFK Malmö',
    field: {
      id: '402',
      name: 'Plan 2',
      arena: {
        id: '502',
        arenaName: 'Helsingborg Arena',
      },
    },
    matchCategory: {
      id: '601',
      name: 'Division 1',
      categoryCode: 'DIV1',
    },
    matchGroup: {
      id: '701',
      displayName: 'Grupp A',
      name: 'Group A',
    },
    matchUrl: 'https://www.profixio.com/match/2',
    matchDataUpdated: '2024-03-16T20:00:00Z',
    resultsUpdated: '2024-03-16T20:00:00Z',
    sets: [
      { home: 22, away: 25 },
      { home: 25, away: 23 },
      { home: 20, away: 25 },
      { home: 18, away: 25 },
    ],
    periodInfo: {
      periodLength: 45,
      slotLength: 15,
      numberOfPeriods: 2,
      pauseLength: 15,
      extraPeriodLength: null,
    },
    isGroupPlay: true,
    isLeaguePlay: false,
    isPlayoff: false,
  },
  {
    id: '3',
    tournamentId: '101',
    number: '3',
    name: 'Match 3',
    gameRound: 2,
    date: '2024-03-22',
    time: '19:00:00',
    datetimeStart: '2024-03-22T19:00:00Z',
    homeTeam: {
      teamRegistrationId: '201',
      globalTeamId: '301',
      name: 'IFK Malmö',
      goals: null,
      isWinner: false,
    },
    awayTeam: {
      teamRegistrationId: '204',
      globalTeamId: '304',
      name: 'Lund FF',
      goals: null,
      isWinner: false,
    },
    hasWinner: false,
    winnerTeam: null,
    field: {
      id: '401',
      name: 'Plan 1',
      arena: {
        id: '501',
        arenaName: 'Malmö Arena',
      },
    },
    matchCategory: {
      id: '601',
      name: 'Division 1',
      categoryCode: 'DIV1',
    },
    matchGroup: {
      id: '701',
      displayName: 'Grupp A',
      name: 'Group A',
    },
    matchUrl: 'https://www.profixio.com/match/3',
    matchDataUpdated: '2024-03-20T10:00:00Z',
    resultsUpdated: null,
    sets: [],
    periodInfo: {
      periodLength: 45,
      slotLength: 15,
      numberOfPeriods: 2,
      pauseLength: 15,
      extraPeriodLength: null,
    },
    isGroupPlay: true,
    isLeaguePlay: false,
    isPlayoff: false,
  },
  {
    id: '4',
    tournamentId: '101',
    number: '4',
    name: 'Match 4',
    gameRound: 2,
    date: '2024-03-23',
    time: '15:00:00',
    datetimeStart: '2024-03-23T15:00:00Z',
    homeTeam: {
      teamRegistrationId: '205',
      globalTeamId: '305',
      name: 'Trelleborgs FF',
      goals: 1,
      isWinner: false,
    },
    awayTeam: {
      teamRegistrationId: '201',
      globalTeamId: '301',
      name: 'IFK Malmö',
      goals: 2,
      isWinner: true,
    },
    hasWinner: true,
    winnerTeam: 'IFK Malmö',
    field: {
      id: '403',
      name: 'Huvudplan',
      arena: {
        id: '503',
        arenaName: 'Trelleborg Arena',
      },
    },
    matchCategory: {
      id: '601',
      name: 'Division 1',
      categoryCode: 'DIV1',
    },
    matchGroup: {
      id: '701',
      displayName: 'Grupp A',
      name: 'Group A',
    },
    matchUrl: 'https://www.profixio.com/match/4',
    matchDataUpdated: '2024-03-23T17:00:00Z',
    resultsUpdated: '2024-03-23T17:00:00Z',
    sets: [
      { home: 25, away: 27 },
      { home: 20, away: 25 },
    ],
    periodInfo: {
      periodLength: 45,
      slotLength: 15,
      numberOfPeriods: 2,
      pauseLength: 15,
      extraPeriodLength: null,
    },
    isGroupPlay: true,
    isLeaguePlay: false,
    isPlayoff: false,
  },
  {
    id: '5',
    tournamentId: '101',
    number: '5',
    name: 'Match 5',
    gameRound: 3,
    date: '2024-03-29',
    time: '18:00:00',
    datetimeStart: '2024-03-29T18:00:00Z',
    homeTeam: {
      teamRegistrationId: '201',
      globalTeamId: '301',
      name: 'IFK Malmö',
      goals: 5,
      isWinner: true,
    },
    awayTeam: {
      teamRegistrationId: '206',
      globalTeamId: '306',
      name: 'Landskrona BoIS',
      goals: 0,
      isWinner: false,
    },
    hasWinner: true,
    winnerTeam: 'IFK Malmö',
    field: {
      id: '401',
      name: 'Plan 1',
      arena: {
        id: '501',
        arenaName: 'Malmö Arena',
      },
    },
    matchCategory: {
      id: '601',
      name: 'Division 1',
      categoryCode: 'DIV1',
    },
    matchGroup: {
      id: '701',
      displayName: 'Grupp A',
      name: 'Group A',
    },
    matchUrl: 'https://www.profixio.com/match/5',
    matchDataUpdated: '2024-03-29T20:00:00Z',
    resultsUpdated: '2024-03-29T20:00:00Z',
    sets: [
      { home: 25, away: 15 },
      { home: 25, away: 18 },
    ],
    periodInfo: {
      periodLength: 45,
      slotLength: 15,
      numberOfPeriods: 2,
      pauseLength: 15,
      extraPeriodLength: null,
    },
    isGroupPlay: true,
    isLeaguePlay: false,
    isPlayoff: false,
  },
  {
    id: '6',
    tournamentId: '101',
    number: '6',
    name: 'Match 6',
    gameRound: 3,
    date: '2024-03-30',
    time: '16:00:00',
    datetimeStart: '2024-03-30T16:00:00Z',
    homeTeam: {
      teamRegistrationId: '207',
      globalTeamId: '307',
      name: 'Östers IF',
      goals: 2,
      isWinner: true,
    },
    awayTeam: {
      teamRegistrationId: '201',
      globalTeamId: '301',
      name: 'IFK Malmö',
      goals: 1,
      isWinner: false,
    },
    hasWinner: true,
    winnerTeam: 'Östers IF',
    field: {
      id: '404',
      name: 'Stadion',
      arena: {
        id: '504',
        arenaName: 'Östers Arena',
      },
    },
    matchCategory: {
      id: '601',
      name: 'Division 1',
      categoryCode: 'DIV1',
    },
    matchGroup: {
      id: '701',
      displayName: 'Grupp A',
      name: 'Group A',
    },
    matchUrl: 'https://www.profixio.com/match/6',
    matchDataUpdated: '2024-03-30T18:00:00Z',
    resultsUpdated: '2024-03-30T18:00:00Z',
    sets: [
      { home: 25, away: 22 },
      { home: 23, away: 25 },
      { home: 25, away: 20 },
    ],
    periodInfo: {
      periodLength: 45,
      slotLength: 15,
      numberOfPeriods: 2,
      pauseLength: 15,
      extraPeriodLength: null,
    },
    isGroupPlay: true,
    isLeaguePlay: false,
    isPlayoff: false,
  },
  {
    id: '7',
    tournamentId: '101',
    number: '7',
    name: 'Match 7',
    gameRound: 4,
    date: '2024-04-05',
    time: '19:30:00',
    datetimeStart: '2024-04-05T19:30:00Z',
    homeTeam: {
      teamRegistrationId: '201',
      globalTeamId: '301',
      name: 'IFK Malmö',
      goals: null,
      isWinner: false,
    },
    awayTeam: {
      teamRegistrationId: '208',
      globalTeamId: '308',
      name: 'Kalmar FF',
      goals: null,
      isWinner: false,
    },
    hasWinner: false,
    winnerTeam: null,
    field: {
      id: '401',
      name: 'Plan 1',
      arena: {
        id: '501',
        arenaName: 'Malmö Arena',
      },
    },
    matchCategory: {
      id: '601',
      name: 'Division 1',
      categoryCode: 'DIV1',
    },
    matchGroup: {
      id: '701',
      displayName: 'Grupp A',
      name: 'Group A',
    },
    matchUrl: 'https://www.profixio.com/match/7',
    matchDataUpdated: '2024-04-03T10:00:00Z',
    resultsUpdated: null,
    sets: [],
    periodInfo: {
      periodLength: 45,
      slotLength: 15,
      numberOfPeriods: 2,
      pauseLength: 15,
      extraPeriodLength: null,
    },
    isGroupPlay: true,
    isLeaguePlay: false,
    isPlayoff: false,
  },
  {
    id: '8',
    tournamentId: '101',
    number: '8',
    name: 'Match 8',
    gameRound: 4,
    date: '2024-04-06',
    time: '14:00:00',
    datetimeStart: '2024-04-06T14:00:00Z',
    homeTeam: {
      teamRegistrationId: '209',
      globalTeamId: '309',
      name: 'Falkenbergs FF',
      goals: 0,
      isWinner: false,
    },
    awayTeam: {
      teamRegistrationId: '201',
      globalTeamId: '301',
      name: 'IFK Malmö',
      goals: 3,
      isWinner: true,
    },
    hasWinner: true,
    winnerTeam: 'IFK Malmö',
    field: {
      id: '405',
      name: 'Huvudplan',
      arena: {
        id: '505',
        arenaName: 'Falkenberg Arena',
      },
    },
    matchCategory: {
      id: '601',
      name: 'Division 1',
      categoryCode: 'DIV1',
    },
    matchGroup: {
      id: '701',
      displayName: 'Grupp A',
      name: 'Group A',
    },
    matchUrl: 'https://www.profixio.com/match/8',
    matchDataUpdated: '2024-04-06T16:00:00Z',
    resultsUpdated: '2024-04-06T16:00:00Z',
    sets: [
      { home: 18, away: 25 },
      { home: 20, away: 25 },
    ],
    periodInfo: {
      periodLength: 45,
      slotLength: 15,
      numberOfPeriods: 2,
      pauseLength: 15,
      extraPeriodLength: null,
    },
    isGroupPlay: true,
    isLeaguePlay: false,
    isPlayoff: false,
  },
  {
    id: '9',
    tournamentId: '101',
    number: '9',
    name: 'Match 9',
    gameRound: 5,
    date: '2024-04-12',
    time: '18:00:00',
    datetimeStart: '2024-04-12T18:00:00Z',
    homeTeam: {
      teamRegistrationId: '201',
      globalTeamId: '301',
      name: 'IFK Malmö',
      goals: 2,
      isWinner: false,
    },
    awayTeam: {
      teamRegistrationId: '210',
      globalTeamId: '310',
      name: 'Halmstads BK',
      goals: 2,
      isWinner: false,
    },
    hasWinner: false,
    winnerTeam: null,
    field: {
      id: '401',
      name: 'Plan 1',
      arena: {
        id: '501',
        arenaName: 'Malmö Arena',
      },
    },
    matchCategory: {
      id: '601',
      name: 'Division 1',
      categoryCode: 'DIV1',
    },
    matchGroup: {
      id: '701',
      displayName: 'Grupp A',
      name: 'Group A',
    },
    matchUrl: 'https://www.profixio.com/match/9',
    matchDataUpdated: '2024-04-12T20:00:00Z',
    resultsUpdated: '2024-04-12T20:00:00Z',
    sets: [
      { home: 25, away: 23 },
      { home: 22, away: 25 },
      { home: 25, away: 25 },
    ],
    periodInfo: {
      periodLength: 45,
      slotLength: 15,
      numberOfPeriods: 2,
      pauseLength: 15,
      extraPeriodLength: null,
    },
    isGroupPlay: true,
    isLeaguePlay: false,
    isPlayoff: false,
  },
  {
    id: '10',
    tournamentId: '101',
    number: '10',
    name: 'Match 10',
    gameRound: 5,
    date: '2024-04-13',
    time: '17:00:00',
    datetimeStart: '2024-04-13T17:00:00Z',
    homeTeam: {
      teamRegistrationId: '211',
      globalTeamId: '311',
      name: 'BK Häcken',
      goals: 1,
      isWinner: false,
    },
    awayTeam: {
      teamRegistrationId: '201',
      globalTeamId: '301',
      name: 'IFK Malmö',
      goals: 4,
      isWinner: true,
    },
    hasWinner: true,
    winnerTeam: 'IFK Malmö',
    field: {
      id: '406',
      name: 'Bravida Arena',
      arena: {
        id: '506',
        arenaName: 'Bravida Arena',
      },
    },
    matchCategory: {
      id: '601',
      name: 'Division 1',
      categoryCode: 'DIV1',
    },
    matchGroup: {
      id: '701',
      displayName: 'Grupp A',
      name: 'Group A',
    },
    matchUrl: 'https://www.profixio.com/match/10',
    matchDataUpdated: '2024-04-13T19:00:00Z',
    resultsUpdated: '2024-04-13T19:00:00Z',
    sets: [
      { home: 20, away: 25 },
      { home: 25, away: 27 },
      { home: 18, away: 25 },
    ],
    periodInfo: {
      periodLength: 45,
      slotLength: 15,
      numberOfPeriods: 2,
      pauseLength: 15,
      extraPeriodLength: null,
    },
    isGroupPlay: true,
    isLeaguePlay: false,
    isPlayoff: false,
  },
];
